[auth]
redirect_uri = "http://localhost:8501/oauth2callback"

[auth.google]
client_id = "183224807-7ihpjah957cqpaf21e1s3e92iqhhp4b5.apps.googleussercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"